# Generated by Django 4.0.4 on 2022-05-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_Birth', models.DateField(blank=True, null=True)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notvisited', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.TextField(blank=True, null=True)),
                ('dieases', models.TextField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('operations', models.TextField(blank=True, null=True)),
                ('currentmedications', models.TextField(blank=True, null=True)),
                ('Exercise', models.CharField(blank=True, max_length=100, null=True)),
                ('Eating', models.CharField(blank=True, max_length=100, null=True)),
                ('Alcohol', models.CharField(blank=True, max_length=100, null=True)),
                ('smoke', models.CharField(blank=True, max_length=100, null=True)),
                ('Caffeine', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
