# Generated by Django 4.0.4 on 2022-05-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dateofvisit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
